on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: root
        server: 142.93.7.105
        port: 22 # default is 22
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        # will put all file under this path
        local_path: ./* # default is ./*
        # files will copy to under remote_path
        remote_path: /var/www/html/test-env/production/
        
        # sftp args
        args: '-o ConnectTimeout=5'